

const List<String> galleryImages = [
  'https://i0.wp.com/thenerddaily.com/wp-content/uploads/2018/08/Reasons-To-Watch-Anime.jpg?resize=768%2C570&ssl=1',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWorObBbfthlVcqo-8j89yv1FRETC5luuvzjuC5KKLJBs4Jp3hD33ZwlcP8RExROnf4sA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdMYkyd_XqHcDqErnx5IeFpQm3Ho03pN3MmA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSawIw-68GqOorQalWWM_MnF-97uxV-y2C30w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8w7Aw9jA9E1ZJJ35_ZeopdF-csVUONyuQaA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQms-IRPmNpWFY1tzRYb_XzU_ZizwimC8r9MCxbDatZOOOs_hWWpTuwH7qTHc5Wc-iWw5M&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5iZ91lS7kI2hoix1gTBazznEMvmMs7Wof8qXyYy5tdmry39lIpo3D5Ro7uS_nqp4l3hk&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmybdlxpWS7vUYSpWV22MFLiNnF4-PVfOhKENb_bbfFfONiEWC3yb-Fet2uaLegNT1Zr0&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMcgMuN2zW7DSjjd67kL3wHRcWPVSwOU0Psj3o9maaKbx8R3rMo8dEhUl2ht8GGL2Nt48&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeMAY3Z-205kWN7XF5u2F8GdNrSs6-RvcMOw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvraC4lPk6WmB4dgw6167g7QMm9QPNQoVRhQ&usqp=CAU',
  'https://imgeng.jagran.com/images/2022/dec/Best%20Gaming%20PC1670400998224.jpg',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo_bHEioD7IjJ1RapG8c1nzv43vBIQWxVlWQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUeVnWhP_jKlE0uHd72gh0vERHSKBHjJHtTxUpz7dHODvysF3W_vo0UVrTUHF5qK_X1Fw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMmJXbjY-43mRxzsxgj5MOcKheYXhzG5aNZg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKbo0mq3PS1WLybkIeMPm0gIbVUrr8xvm1vg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS99h-Fp6VSHQ6Zf3wid_-7quuREw7bSKjoxQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd4lC58a0U5SkjRZIrDskBi7UA2oLoERSfvOHjh6EFoRqMTnibXMaaMVwytIcyTElFmIU&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA_0H03f9SAD7xRhoEhKzbb0JVhpR-ZluMGQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCAUyt_LnRFw8OlGom1P3RejpnFk9CBomr2Q&usqp=CAU',
  'https://i0.wp.com/thenerddaily.com/wp-content/uploads/2018/08/Reasons-To-Watch-Anime.jpg?resize=768%2C570&ssl=1',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWorObBbfthlVcqo-8j89yv1FRETC5luuvzjuC5KKLJBs4Jp3hD33ZwlcP8RExROnf4sA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdMYkyd_XqHcDqErnx5IeFpQm3Ho03pN3MmA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSawIw-68GqOorQalWWM_MnF-97uxV-y2C30w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8w7Aw9jA9E1ZJJ35_ZeopdF-csVUONyuQaA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQms-IRPmNpWFY1tzRYb_XzU_ZizwimC8r9MCxbDatZOOOs_hWWpTuwH7qTHc5Wc-iWw5M&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5iZ91lS7kI2hoix1gTBazznEMvmMs7Wof8qXyYy5tdmry39lIpo3D5Ro7uS_nqp4l3hk&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmybdlxpWS7vUYSpWV22MFLiNnF4-PVfOhKENb_bbfFfONiEWC3yb-Fet2uaLegNT1Zr0&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMcgMuN2zW7DSjjd67kL3wHRcWPVSwOU0Psj3o9maaKbx8R3rMo8dEhUl2ht8GGL2Nt48&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeMAY3Z-205kWN7XF5u2F8GdNrSs6-RvcMOw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvraC4lPk6WmB4dgw6167g7QMm9QPNQoVRhQ&usqp=CAU',
  'https://imgeng.jagran.com/images/2022/dec/Best%20Gaming%20PC1670400998224.jpg',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo_bHEioD7IjJ1RapG8c1nzv43vBIQWxVlWQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUeVnWhP_jKlE0uHd72gh0vERHSKBHjJHtTxUpz7dHODvysF3W_vo0UVrTUHF5qK_X1Fw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMmJXbjY-43mRxzsxgj5MOcKheYXhzG5aNZg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKbo0mq3PS1WLybkIeMPm0gIbVUrr8xvm1vg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS99h-Fp6VSHQ6Zf3wid_-7quuREw7bSKjoxQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd4lC58a0U5SkjRZIrDskBi7UA2oLoERSfvOHjh6EFoRqMTnibXMaaMVwytIcyTElFmIU&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA_0H03f9SAD7xRhoEhKzbb0JVhpR-ZluMGQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCAUyt_LnRFw8OlGom1P3RejpnFk9CBomr2Q&usqp=CAU',

];

const List<String> audioList = [
  'https://img.wynk.in/unsafe/248x248/filters:no_upscale():strip_exif():format(webp)/http://s3.ap-south-1.amazonaws.com/discovery-prod-arsenal/arsenal/artworks/6598076eb0ff2a1fcc91e52a/COLLECTION_4676785598342.png',
  'https://upload.wikimedia.org/wikipedia/en/d/d1/Babycoverart.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/ZaP37OR3Dy/P374QGV6WD/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/qaLKY23pO4/LKYAG0vaKp/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/Bp1bAnK029/1bAL445gW0/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/a7LWBkzbzX/LWBkqrnDbz/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/kGxbnw0Ky4/xbn15RZMWy/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/2lV3d1WRgB/V3dZmlBobR/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/2lV3dl13Rg/V3dl28Ox3R/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/Dk9KN2KBx1/9KNgP9Zd3B/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/g4w3vr3jJB/w3v5e8qGKj/size_m.jpg',
  'https://a10.gaanacdn.com/gn_img/albums/81l3Me3rMx/l3MZ8kg1Wr/size_m.jpg',
];


const List<String> audioNameList = [
  'Who I Am',
  'Baby',
  'THINK LATER',
  'Desperado',
  'Scarlet',
  'Car Keys (Ayla)',
  'Used To Be Young',
  'For All The Dogs',
  'TYLA',
  'Jacquemus',
  'TOO MUCH',
  'Pink Friday 2',
];
const List<String> artistsNameList = [
  'Alan Walker, Peder Elias, Putri Ariani',
  'Justin Bieber',
  'Dua Lipa',
  'Raghav,Tesher',
  'Doja Cat',
  'Alok,Ava Max',
  'Miley Cyrus',
  'Drake,Bad Bunny',
  'Tyla',
  'Tesher',
  'The Kid LAROI,Jung Kook,Central Cee',
  'Nicki Minaj',
];

